#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/tomtom/tcomment_vim.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  'git://github.com/Townk/vim-autoclose.git',
  'git://github.com/Lokaltog/vim-powerline.git',
  'git://github.com/vim-scripts/DeleteTrailingWhitespace.git',
  'git://github.com/scrooloose/syntastic.git',
  'git://github.com/tpope/vim-rvm.git',
  'git://github.com/kien/ctrlp.vim.git',
  # 'git://github.com/wincent/Command-T',
  'git://github.com/godlygeek/tabular.git',
  # 'git://github.com/rking/ag.vim.git',
  'git://github.com/tpope/vim-surround.git',
  'git://github.com/tpope/vim-fugitive',
  # 'git://github.com/sjbach/lusty',
  'git://github.com/tpope/vim-rails.git',
  'git://github.com/tpope/vim-haml.git',
  'git://github.com/tpope/vim-markdown.git',
  'git://github.com/tpope/vim-bundler.git',
  'git://github.com/t9md/vim-chef.git',
  'git://github.com/kchmck/vim-coffee-script.git',
  # 'git://github.com/othree/javascript-libraries-syntax.vim.git',
  'git://github.com/cakebaker/scss-syntax.vim.git',
  'git@github.com:thoughtbot/vim-rspec.git',
  'git@github.com:ngmy/vim-rubocop.git',
  'git@github.com:mileszs/ack.vim.git',
  'git://github.com/AndrewRadev/vim-eco',
  'git://github.com/joequery/Stupid-EasyMotion',
  'git@github.com:briancollins/vim-jst.git',
  'https://github.com/airblade/vim-rooter',
  'https://github.com/fatih/vim-go'
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.mkdir_p(bundles_dir)

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`

  if dir == 'YouCompleteMe'
    FileUtils.cd(dir)
    `git submodule update --init --recursive`
    `./install.sh`
    `find . -name ".git"|xargs rm -rf`
    # `./install.sh --clang-completer`
  end

  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
